name: "MieleXKM3100WGateway for Home Assistant"
description: "MieleXKM3100WGateway for Home Assistant"
version: "2.2.0"
slug: "miele_gateway"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 3000
options:
  GROUPID: ""
  GROUPKEY: ""
schema:
  GROUPID: str
  GROUPKEY: str
